### ISSUE TITLE
Crash on server start [1.19.2]

### ISSUE THREAD

**Issue by Angelo-Funelas** [Phelms215/JoinLeaveMessages-Fabric#2]
`13.08 12:18:42 [Server] main/ERROR Mixin apply for mod joinleavemessages failed joinleavemessages.mixins.json:BroadcastChatMessageMixin from mod joinleavemessages -> net.minecraft.class_3324: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on filterBroadCastMessages could not find any targets matching 'Lnet/minecraft/class_3324;method_43514(Lnet/minecraft/class_2561;Lnet/minecraft/class_5321;)V' in net.minecraft.class_3324. Using refmap joinleavemessages-refmap.json [PREINJECT Applicator Phase -> joinleavemessages.mixins.json:BroadcastChatMessageMixin from mod joinleavemessages -> Prepare Injections ->  -> handler$zhk000$filterBroadCastMessages(Lnet/minecraft/class_2561;Lnet/minecraft/class_5321;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
13.08 12:18:42 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on filterBroadCastMessages could not find any targets matching 'Lnet/minecraft/class_3324;method_43514(Lnet/minecraft/class_2561;Lnet/minecraft/class_5321;)V' in net.minecraft.class_3324. Using refmap joinleavemessages-refmap.json [PREINJECT Applicator Phase -> joinleavemessages.mixins.json:BroadcastChatMessageMixin from mod joinleavemessages -> Prepare Injections ->  -> handler$zhk000$filterBroadCastMessages(Lnet/minecraft/class_2561;Lnet/minecraft/class_5321;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at jdk.internal.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source) ~[?:?]
13.08 12:18:42 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
13.08 12:18:42 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
13.08 12:18:42 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
13.08 12:18:42 [Server] INFO at net.minecraft.server.Main.method_29734(Main.java:211) ~[server-intermediary.jar:?]
13.08 12:18:42 [Server] INFO at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:264) [server-intermediary.jar:?]
13.08 12:18:42 [Server] INFO at net.minecraft.server.Main.main(Main.java:210) [server-intermediary.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.9-launcher.0.11.0.jar:0.11.0]
13.08 12:18:42 [Server] main/ERROR Failed to start the minecraft server
13.08 12:18:42 [Server] INFO java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
13.08 12:18:42 [Server] INFO at net.minecraft.server.Main.method_29734(Main.java:211) ~[server-intermediary.jar:?]
13.08 12:18:42 [Server] INFO at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:264) ~[server-intermediary.jar:?]
13.08 12:18:42 [Server] INFO at net.minecraft.server.Main.main(Main.java:210) [server-intermediary.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.9-launcher.0.11.0.jar:0.11.0]
13.08 12:18:42 [Server] INFO Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO ... 12 more
13.08 12:18:42 [Server] INFO Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [joinleavemessages.mixins.json:BroadcastChatMessageMixin from mod joinleavemessages] from phase [DEFAULT] in config [joinleavemessages.mixins.json] FAILED during APPLY
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO ... 12 more
13.08 12:18:42 [Server] INFO Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on filterBroadCastMessages could not find any targets matching 'Lnet/minecraft/class_3324;method_43514(Lnet/minecraft/class_2561;Lnet/minecraft/class_5321;)V' in net.minecraft.class_3324. Using refmap joinleavemessages-refmap.json [PREINJECT Applicator Phase -> joinleavemessages.mixins.json:BroadcastChatMessageMixin from mod joinleavemessages -> Prepare Injections ->  -> handler$zhk000$filterBroadCastMessages(Lnet/minecraft/class_2561;Lnet/minecraft/class_5321;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at jdk.internal.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source) ~[?:?]
13.08 12:18:42 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
13.08 12:18:42 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
13.08 12:18:42 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
13.08 12:18:42 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
13.08 12:18:42 [Server] INFO ... 12
`

**Comment by Phelms215** [comment]
1.19.2 update should be out this weekend

**Comment by ZachTheDev** [comment]
@Phelms215 I am not seeing the update. Any chance you got to work on it?

**Comment by Phelms215** [comment]
Update was pushed today - sorry for the delay.

On github now, should be on Modrinth/Curseforge shortly (after their review period)
